### ISSUE TITLE
Why http:// works and not https:// ?

### ISSUE THREAD

**Issue by Rixuel** [churchio/bible_api#15]
Hello,

When I try to access **https**://bible-api.com, it doesn't work, it's saying the connection is not secure (I tried on both Firefox and Chrome)

When I go to **http**://bible-api.com, everything is fine.

Why is that?

From a http:// website, I can get api data from their http and https url.
But from a https:// website, I can only get data from https url but not http url.

**Comment by hunternet93** [comment]
It looks like the security certificate used for bible-api.com is only valid for the server's primary domain. It's a bit difficult to fix without multiple server IPs or multiple servers, unfortunately. It should be safe to ignore the certificate error, the connection will still be encrypted although application code would be unable to fully verify the server's identity.

**Comment by Rixuel** [comment]
Oh, looks like https://bible-api.com works now :+1: 

Thank you very much :3

**Comment by hunternet93** [comment]
The domain is now running from a different IP and has its own certificate, looks like @seven1m fixed it.

**Comment by seven1m** [comment]
Yep, fixed!
