### ISSUE TITLE
Leaves out part of Joshua 24:15

### ISSUE THREAD

**Issue by superMDguy** [churchio/bible_api#17]
I was testing out the api a bit, and I tried putting in Joshua 24:15, using the kjv translation: [url I put in](https://bible-api.com/Joshua 24:15?translation=kjv).  For some reason, it left out the "we will serve the LORD" part, which you can see [here](https://www.biblegateway.com/passage/?search=Joshua+24%3A15&version=KJV).  Is this just an issue with the open bibles repository, or is it something you can fix?

**Comment by seven1m** [comment]
That's wild. I'll take a look!

**Comment by seven1m** [comment]
OK, this is fixed! Turns out some longer verses were getting truncated. 😬 But we're all fixed now.

**Comment by superMDguy** [comment]
Ok, thanks!
