### ISSUE TITLE
Is Bible reading range possible?

### ISSUE THREAD

**Issue by twonjee2002** [churchio/bible_api#20]
I am trying out the bible api and I must confess it is a great one. I would like to ask if it is possible to read from the verse of a chapter to a verse of another chapter. I have tried this but could not figure it out. I mean something like:

https://bible-api.com/john 3:16 - 4:10

I hope to hear from you soon.

Thanks.

**Comment by seven1m** [comment]
https://bible-api.com/john+3:16-4:10 works.

**Comment by twonjee2002** [comment]
Thanks will try this.
