### ISSUE TITLE
Bible API

### ISSUE THREAD

**Issue by pinckneyjjp** [churchio/bible_api#21]
Cool API, thanks!

Any way to "reference" the books by index number or position in an array - rather than by name?

**Comment by seven1m** [comment]
Not currently, but that should be possible to add. I'll see what I can do.

**Comment by pinckneyjjp** [comment]
My work-around:  I made an array of books with "name:value-pairs"  of {"1:Genesis", "2:Exodus", ..."n:name"}  . 

Now I am thinking of a "for loop" to pull down whole chapters at a time. 

Just learning my javascript here :-) 

John

**Comment by seven1m** [comment]
@pinckneyjjp if your goal is just to fetch the entire bible from the API, you might be more interested in our [bible_parser](https://github.com/churchio/bible_parser) project.

Then you could do this in Ruby:

```ruby
require 'bible_parser'

bible = BibleParser.new(File.open('web.usfx.xml'))
bible.books.each do |book|
  book.chapters.each do |chapter|
    chapter.verses.each do |verse|
      p verse.to_h
      # yields:
      # {
      #   num: 1,
      #   book_id: "GEN",
      #   book_num: 1,
      #   book_title: "Genesis",
      #   chapter_num: 1,
      #   text: "In the beginning, God created the heavens and the earth.\n"
      # }
    end
  end
end
```

You could even convert an entire book to JSON with something like this:

```ruby
require 'json'
require 'bible_parser'

bible = BibleParser.new(File.open('web.usfx.xml'))
book = bible.books.first # genesis

book.chapters.map { |c| c.verses.map { |v| v.to_h } }.to_json
```

Hitting the API for every chapter, one-at-a-time, will be slow.

(Also, if you degrade the service for others, I'll probably end up blocking your IP 😬)

**Comment by pinckneyjjp** [comment]
No need to block me: I'll take your hint.   I will practice my javascript by other means and get back to your site after learning a bit more rails.  Thanks!
