### ISSUE TITLE
Add whole book and whole bible ranges

### ISSUE THREAD

**Issue by csf30816** [churchio/bible_api#23]
I noticed if you do `https://bible-api.com/john` it reports `not found`. It would really help if when you do `https://bible-api.com/john` it would report the whole book of john, and when you put `https://bible-api.com/bible` it would report the whole bible. Thanks.

**Comment by seven1m** [comment]
@csf30816 the use-case of the API is not really to download an entire book or entire bible. For that, you might be interested in our [bible_parser](https://github.com/churchio/bible_parser) project -- you can use it to read in the entire bible XML file and do whatever you want with the data. Hope that helps!

**Comment by csf30816** [comment]
OK, thanks
