### ISSUE TITLE
Query Translated Book Name

### ISSUE THREAD

**Issue by gustavobim** [churchio/bible_api#4]
I was checking the http://bible-api.com/ and I can see you have some translations available now. Example: http://bible-api.com/john+3:16?translation=almeida

Is there a way to query directly from the translated book name? In this example it should be João 3:16 for the almeida version.

**Comment by seven1m** [comment]
Not yet, but I'll work on adding that!

**Comment by gustavobim** [comment]
thanks Tim! You are the best! :+1:

**Comment by seven1m** [comment]
@gustavobim this works now: http://bible-api.com/João+3:16?translation=almeida

**Comment by gustavobim** [comment]
Amazing! Thanks Tim. I will check this out.
