### ISSUE TITLE
Fetch all verses by a book

### ISSUE THREAD

**Issue by marcelodeveloper** [churchio/bible_api#6]
Do you have some route to get all verses by a chapter?
---------------------------------------------------------------

When do i access http://api.com/{book} the return is empty or not found

```sh
$ http://bible-api.com/{book}
```

*this will return all verses!*

**Comment by seven1m** [comment]
@marcelodeveloper I don't think that's a use-case I'd like to support. At the point you're pulling down entire books of the bible, you'd be better off using [bible_parser](https://github.com/churchio/bible_parser) and getting the raw data yourself.

I'd rather not put the extra load on my server to support this case.

**Comment by marcelodeveloper** [comment]
Ok @seven1m, but if the user to wants select a chapter and then a verse? I'm thinking in this scenario.

**Comment by seven1m** [comment]
@marcelodeveloper I'm confused by what you mean. You can already fetch an entire chapter, e.g. http://bible-api.com/John+3

Fetching an entire book isn't something I think this application needs to support.
