### ISSUE TITLE
Jude - not found

### ISSUE THREAD

**Issue by bryanvam** [churchio/bible_api#7]
http://bible-api.com/Jude 1-25

**Comment by seven1m** [comment]
http://bible-api.com/jude+1:1-25 works. I should make an exception for Jude and not require the chapter number. I'll leave this issue open.

**Comment by seven1m** [comment]
Fixed with https://github.com/churchio/bible_ref/commit/e90da2a470ba0fd7ced323cfe0b27ee16e1103a2

**Comment by seven1m** [comment]
Will be deployed to bible-api.com soon....
